
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.StringTokenizer;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ghifa
 */
public class Rtranpage extends javax.swing.JFrame {

    /**
     * Creates new form Rtranpage
     */
    public String ganti = "";
    public StringTokenizer token;
    public long angka;

    public Rtranpage() {
        initComponents();
        ThirdPages.juTable();
        setLocationRelativeTo(null);
        autosum();
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 40, 40));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        RTtable = new javax.swing.JTable();
        Kt = new javax.swing.JTextField();
        Kt1 = new javax.swing.JTextField();
        Kt2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RTtable.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 16)); // NOI18N
        RTtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        RTtable.setEnabled(false);
        RTtable.setFocusable(false);
        RTtable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        RTtable.setRowHeight(25);
        RTtable.setSelectionBackground(new java.awt.Color(255, 102, 153));
        RTtable.setShowVerticalLines(false);
        RTtable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(RTtable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 1110, 470));

        Kt.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        Kt.setForeground(new java.awt.Color(153, 153, 153));
        Kt.setText("Kode Transaksi");
        Kt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                KtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                KtFocusLost(evt);
            }
        });
        Kt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KtActionPerformed(evt);
            }
        });
        Kt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KtKeyPressed(evt);
            }
        });
        getContentPane().add(Kt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 260, 40));

        Kt1.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        Kt1.setForeground(new java.awt.Color(153, 153, 153));
        Kt1.setText("Nama Pembeli");
        Kt1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Kt1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Kt1FocusLost(evt);
            }
        });
        Kt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kt1ActionPerformed(evt);
            }
        });
        Kt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Kt1KeyPressed(evt);
            }
        });
        getContentPane().add(Kt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 260, 40));

        Kt2.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        Kt2.setForeground(new java.awt.Color(153, 153, 153));
        Kt2.setText("Tgl Transaksi(yyyy-mm-dd)");
        Kt2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Kt2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Kt2FocusLost(evt);
            }
        });
        Kt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kt2ActionPerformed(evt);
            }
        });
        Kt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Kt2KeyPressed(evt);
            }
        });
        getContentPane().add(Kt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 260, 40));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Search  :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Total Pendapatan :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 690, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 30)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("___________");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 740, 340, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("___________________________");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 790, -1, 40));

        jLabel16.setFont(new java.awt.Font("Nirmala UI", 0, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("X");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
        });
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 10, -1, -1));

        jLabel15.setFont(new java.awt.Font("Nirmala UI", 0, 80)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("-");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 10, -1, 40));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IniGmbr/NIew/serb.png"))); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 210, 140));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IniGmbr/NIew/Riwayat Transaksi (2).png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void autosum() {
        int ttl = 0;
        for (int i = 0; i < RTtable.getRowCount(); i++) {
            int amount = Integer.parseInt((String) RTtable.getValueAt(i, 3));
            ttl += amount;
        }
        jLabel4.setText("" + ttl);
        angka = Integer.parseInt(jLabel4.getText());
        ganti = NumberFormat.getNumberInstance(Locale.US).format(angka);
        token = new StringTokenizer(ganti, ".");
        ganti = token.nextToken();
        ganti = ganti.replace(',', '.');
        jLabel4.setText("Rp. " + String.format(ganti));
    }
    private void KtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KtActionPerformed

    private void Kt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Kt1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        for (double i = 0.0; i <= 1.0; i = i + 0.1) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(25);
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void KtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KtFocusGained
        // TODO add your handling code here:
        if (Kt.getText().equals("Kode Transaksi")) {
            Kt.setText("");
            Kt.setForeground(new Color(0));
        }
    }//GEN-LAST:event_KtFocusGained

    private void KtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KtFocusLost
        // TODO add your handling code here:
        if (Kt.getText().equals("")) {
            Kt.setText("Kode Transaksi");
            Kt.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_KtFocusLost

    private void Kt1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Kt1FocusGained
        // TODO add your handling code here:
        if (Kt1.getText().equals("Nama Pembeli")) {
            Kt1.setText("");
            Kt1.setForeground(new Color(0));
        }
    }//GEN-LAST:event_Kt1FocusGained

    private void Kt1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Kt1FocusLost
        // TODO add your handling code here:
        if (Kt1.getText().equals("")) {
            Kt1.setText("Nama Pembeli");
            Kt1.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_Kt1FocusLost

    private void Kt2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Kt2FocusGained
        // TODO add your handling code here:
        if (Kt2.getText().equals("Tgl Transaksi(yyyy-mm-dd)")) {
            Kt2.setText("");
            Kt2.setForeground(new Color(0));
        }
    }//GEN-LAST:event_Kt2FocusGained

    private void Kt2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Kt2FocusLost
        // TODO add your handling code here:
        if (Kt2.getText().equals("")) {
            Kt2.setText("Tgl Transaksi(yyyy-mm-dd)");
            Kt2.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_Kt2FocusLost

    private void Kt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Kt2ActionPerformed

    private void KtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //jLabel6.getFocusListeners();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            Kt1.requestFocus();
        }

    }//GEN-LAST:event_KtKeyPressed

    private void Kt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Kt1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //Car.doClick();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            Kt.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            Kt2.requestFocus();
        }
    }//GEN-LAST:event_Kt1KeyPressed

    private void Kt2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Kt2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //Car.doClick();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            Kt1.requestFocus();
        }
    }//GEN-LAST:event_Kt2KeyPressed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        // TODO add your handling code here:
        jLabel16.setForeground(Color.red);
    }//GEN-LAST:event_jLabel16MouseEntered

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
        // TODO add your handling code here:
        jLabel16.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_jLabel16MouseExited

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        // TODO add your handling code here:
        jLabel15.setForeground(Color.red);
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        // TODO add your handling code here:
        jLabel15.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_jLabel15MouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        try {
            String sql = "select * from transaksi where "
                    + "Kode_Transaksi ='" + Kt.getText() + "' || Nama_Pembeli = '" + Kt1.getText() + "' || Tanggal_Transaksi = '" + Kt2.getText() + "' ";

            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.PreparedStatement stm = conn.prepareStatement(sql);
            java.sql.ResultSet res = stm.executeQuery();
            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("Kode_Tran");
            tbl.addColumn("Nama_Pembeli");
            tbl.addColumn("No Meja");
            tbl.addColumn("Grand_Total");
            tbl.addColumn("Tanggal_Tran");
            RTtable.setModel(tbl);
            while (res.next()) {
                tbl.addRow(new Object[]{
                    res.getString("Kode_Transaksi"),
                    res.getString("Nama_Pembeli"),
                    res.getString("No_Meja"),
                    res.getString("Grand_Total"),
                    res.getString("Tanggal_Transaksi")
                });
                RTtable.setModel(tbl);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "salah");

        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IniGmbr/NIew/serp.png")));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IniGmbr/NIew/serb.png")));
    }//GEN-LAST:event_jLabel6MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rtranpage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rtranpage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rtranpage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rtranpage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rtranpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Kt;
    private javax.swing.JTextField Kt1;
    private javax.swing.JTextField Kt2;
    public static javax.swing.JTable RTtable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
