
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Font;
import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.StringTokenizer;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ghifa
 */
public class ThirdPages extends javax.swing.JFrame {

    /**
     * Creates new form ThirdPages
     */
    //SecondPage sp = new SecondPage();
    //FourthPages fp = new FourthPages();
    public String ganti = "";
    public StringTokenizer token;
    public long angka;

    public ThirdPages() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Metode Pembayaran");
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 40, 40));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mab = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        np = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nm = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mab.setFont(new java.awt.Font("Segoe Print", 1, 38)); // NOI18N
        mab.setForeground(new java.awt.Color(102, 102, 102));
        mab.setText("0");
        getContentPane().add(mab, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 740, 300, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("Kode Transaksi");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 240, -1));

        kt.setFont(new java.awt.Font("Segoe Print", 1, 20)); // NOI18N
        kt.setForeground(new java.awt.Color(153, 153, 153));
        kt.setText("Tidak boleh sama!!");
        kt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ktFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ktFocusLost(evt);
            }
        });
        kt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ktActionPerformed(evt);
            }
        });
        kt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ktKeyPressed(evt);
            }
        });
        getContentPane().add(kt, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 300, -1));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setText("Nama Pelanggan");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 260, -1));

        np.setFont(new java.awt.Font("Segoe Print", 1, 20)); // NOI18N
        np.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npActionPerformed(evt);
            }
        });
        np.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                npKeyPressed(evt);
            }
        });
        getContentPane().add(np, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 300, -1));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setText("No Meja");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 130, -1));

        nm.setFont(new java.awt.Font("Segoe Print", 1, 20)); // NOI18N
        nm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmActionPerformed(evt);
            }
        });
        nm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nmKeyPressed(evt);
            }
        });
        getContentPane().add(nm, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 300, -1));

        jLabel9.setBackground(new java.awt.Color(0, 204, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 3, 25)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 190, 50));

        jLabel16.setFont(new java.awt.Font("Nirmala UI", 0, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("X");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
        });
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 10, -1, -1));

        jLabel15.setFont(new java.awt.Font("Nirmala UI", 0, 80)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("-");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, -1, 40));

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IniGmbr/NIew/butun0.png"))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 250, 150));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IniGmbr/NIew/bunon1.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 240, 140));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 260, 330, 340));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IniGmbr/NIew/pay3.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static void juTable() {
        Rtranpage.RTtable.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        Rtranpage.RTtable.getTableHeader().setOpaque(true);
        Rtranpage.RTtable.getTableHeader().setBackground(new Color(225, 225, 225));
        Rtranpage.RTtable.getTableHeader().setForeground(new Color(32, 136, 203));
        Rtranpage.RTtable.setRowHeight(25);
        //membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Kode_Transaksi");
        model.addColumn("Kode_Pembayaran");
        model.addColumn("Grand_Total");
        model.addColumn("No_Meja");
        model.addColumn("Tanggal_Transaksi");
        model.addColumn("Nama_Pembeli");
        model.addColumn("ID_Kasir");
        //menampilkan data databse ke dalam table
        try {
            int no = 1;
            String sql = "select * from transaksi";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{no++, res.getString(1),
                    res.getString(2), res.getString(3), res.getString(4), res.getString(5), res.getString(6), res.getString(7)});
            }
            Rtranpage.RTtable.setModel(model);
        } catch (Exception e) {
        }
    }
    private void ktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ktActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ktActionPerformed

    private void npActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_npActionPerformed

    private void nmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmActionPerformed

    private void ktKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ktKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            np.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            np.requestFocus();
        }
    }//GEN-LAST:event_ktKeyPressed

    private void npKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_npKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            nm.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            kt.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            nm.requestFocus();
        }
    }//GEN-LAST:event_npKeyPressed

    private void nmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nmKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            np.requestFocus();
        }
    }//GEN-LAST:event_nmKeyPressed

    private void ktFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ktFocusGained
        // TODO add your handling code here
        if (kt.getText().equals("Tidak boleh sama!!")) {
            kt.setText("");
            kt.setForeground(new Color(0));
        }
    }//GEN-LAST:event_ktFocusGained

    private void ktFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ktFocusLost
        // TODO add your handling code here:
        if (kt.getText().equals("")) {
            kt.setText("Tidak boleh sama!!");
            kt.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_ktFocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        for (double i = 0.0; i <= 1.0; i = i + 0.1) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(25);
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        // TODO add your handling code here:
        jLabel16.setForeground(Color.red);
    }//GEN-LAST:event_jLabel16MouseEntered

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
        // TODO add your handling code here:
        jLabel16.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_jLabel16MouseExited

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        // TODO add your handling code here:
        jLabel15.setForeground(Color.red);
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        // TODO add your handling code here:
        jLabel15.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_jLabel15MouseExited

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IniGmbr/NIew/butun.png")));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IniGmbr/NIew/butun0.png")));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:

        try {
            int no = Integer.parseInt((String) JOptionPane.showInputDialog(null, "Masukkan Nominal Uang", "Input", JOptionPane.QUESTION_MESSAGE));
            int tagi = Integer.parseInt(SecondPage.total.getText());
            int kal = no - tagi;
            if (kal < 0) {
                JOptionPane.showMessageDialog(this, "Nominal uang salah!", "Error", JOptionPane.WARNING_MESSAGE);
            } else {
                try {
                    //Transaksi
                    String sqll = "INSERT INTO transaksi VALUES ('" + kt.getText() + "','001','" + SecondPage.total.getText() + "','" + nm.getText() + "','" + jLabel9.getText() + "','" + np.getText() + "','" + Login.id.getText() + "')";

                    java.sql.Connection conn = (Connection) Config.configDB();

                    java.sql.PreparedStatement pst1 = conn.prepareStatement(sqll);
                    pst1.execute();
                    //Detail Transaksi
                    try {
                        //java.sql.Connection conn = (Connection) Config.configDB();
                        if (SecondPage.men.getText().equalsIgnoreCase("caviar")) {
                            String sql = "INSERT INTO detail_transaksi VALUES('" + kt.getText() + "' ,'01','" + FirstPage.jSpinner1.getModel().getValue().toString() + "','" + SecondPage.ment.getText() + "' )";
                            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                            pst.execute();
                        } else {
                            System.out.println("Detail menu 1 kosong");
                        }
                        if (SecondPage.men2.getText().equalsIgnoreCase("sandwich")) {
                            String sql = "INSERT INTO detail_transaksi VALUES('" + kt.getText() + "' ,'02','" + FirstPage.jSpinner2.getModel().getValue().toString() + "','" + SecondPage.ment2.getText() + "' )";
                            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                            pst.execute();
                        } else {
                            System.out.println("Detail menu 2 kosong");
                        }
                        if (SecondPage.men3.getText().equalsIgnoreCase("french fries")) {
                            String sql = "INSERT INTO detail_transaksi VALUES('" + kt.getText() + "' ,'03','" + FirstPage.jSpinner3.getModel().getValue().toString() + "','" + SecondPage.ment3.getText() + "' )";
                            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                            pst.execute();
                        } else {
                            System.out.println("Detail menu 3 kosong");
                        }
                        if (SecondPage.men4.getText().equalsIgnoreCase("fried rice")) {
                            String sql = "INSERT INTO detail_transaksi VALUES('" + kt.getText() + "' ,'04','" + FirstPage.jSpinner4.getModel().getValue().toString() + "','" + SecondPage.ment4.getText() + "' )";
                            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                            pst.execute();
                        } else {
                            System.out.println("Detail menu 4 kosong");
                        }
                        if (SecondPage.men5.getText().equalsIgnoreCase("Pizza")) {
                            String sql = "INSERT INTO detail_transaksi VALUES('" + kt.getText() + "' ,'09','" + FirstPage.jSpinner5.getModel().getValue().toString() + "','" + SecondPage.ment5.getText() + "' )";
                            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                            pst.execute();
                        } else {
                            System.out.println("Detail menu 5 kosong");
                        }
                        if (SecondPage.men6.getText().equalsIgnoreCase("lemon tea")) {
                            String sql = "INSERT INTO detail_transaksi VALUES('" + kt.getText() + "' ,'06','" + FirstPage.jSpinner6.getModel().getValue().toString() + "','" + SecondPage.ment6.getText() + "' )";
                            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                            pst.execute();
                        } else {
                            System.out.println("Detail menu 6 kosong");
                        }
                        if (SecondPage.men7.getText().equalsIgnoreCase("coffe")) {
                            String sql = "INSERT INTO detail_transaksi VALUES('" + kt.getText() + "' ,'07','" + FirstPage.jSpinner7.getModel().getValue().toString() + "','" + SecondPage.ment7.getText() + "' )";
                            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                            pst.execute();
                        } else {
                            System.out.println("Detail menu 7 kosong");
                        }
                        if (SecondPage.men8.getText().equalsIgnoreCase("tea")) {
                            String sql = "INSERT INTO detail_transaksi VALUES('" + kt.getText() + "' ,'08','" + FirstPage.jSpinner8.getModel().getValue().toString() + "','" + SecondPage.ment8.getText() + "' )";
                            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                            pst.execute();
                        } else {
                            System.out.println("Detail menu 8 kosong");
                        }
                        if (SecondPage.men9.getText().equalsIgnoreCase("Milkshake")) {
                            String sql = "INSERT INTO detail_transaksi VALUES('" + kt.getText() + "' ,'05','" + FirstPage.jSpinner9.getModel().getValue().toString() + "','" + SecondPage.ment9.getText() + "' )";
                            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                            pst.execute();
                        } else {
                            System.out.println("Detail menu 9 kosong");
                        }
                        if (SecondPage.men10.getText().equalsIgnoreCase("soda")) {
                            String sql = "INSERT INTO detail_transaksi VALUES('" + kt.getText() + "' ,'10','" + FirstPage.jSpinner10.getModel().getValue().toString() + "','" + SecondPage.ment10.getText() + "' )";
                            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                            pst.execute();
                        } else {
                            System.out.println("Detail menu 10 kosong");
                        }
                        this.setVisible(false);
                        new FourthPages().setVisible(true);
                        JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Detail Transaksi Error!\n" + e.getMessage());
                    }
                } catch (Exception e) {

                    JOptionPane.showMessageDialog(this, "Transaksi Error!\nTerdapat Kode Transaksi yang Sama!!\n" + e.getMessage());
                }
            }

             if (kal == 0) {
                FourthPages.jLabel1.setText("Uang Pas");
            } else {
                angka = kal;
                ganti = NumberFormat.getNumberInstance(Locale.US).format(angka);
                token = new StringTokenizer(ganti, ".");
                ganti = token.nextToken();
                ganti = ganti.replace(',', '.');
                FourthPages.jLabel1.setText("Rp. " + String.format(ganti));
            }
            FourthPages.jLabel5.setText("Tunai");
        } catch (Exception e) {
            System.out.println("Anda tidak memasukkan nominal");
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        try {

            String sqll = "INSERT INTO transaksi VALUES ('" + kt.getText() + "','002','" + SecondPage.total.getText() + "','" + nm.getText() + "','" + jLabel9.getText() + "','" + np.getText() + "','" + Login.id.getText() + "')";

            java.sql.Connection conn = (Connection) Config.configDB();

            java.sql.PreparedStatement pst1 = conn.prepareStatement(sqll);
            pst1.execute();
            //Detail Transaksi
            try {
                //java.sql.Connection conn = (Connection) Config.configDB();
                if (SecondPage.men.getText().equalsIgnoreCase("caviar")) {
                    String sql = "INSERT INTO detail_transaksi VALUES('" + kt.getText() + "' ,'01','" + FirstPage.jSpinner1.getModel().getValue().toString() + "','" + SecondPage.ment.getText() + "' )";
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                } else {
                    System.out.println("Detail menu 1 kosong");
                }
                if (SecondPage.men2.getText().equalsIgnoreCase("sandwich")) {
                    String sql = "INSERT INTO detail_transaksi VALUES('" + kt.getText() + "' ,'02','" + FirstPage.jSpinner2.getModel().getValue().toString() + "','" + SecondPage.ment2.getText() + "' )";
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                } else {
                    System.out.println("Detail menu 2 kosong");
                }
                if (SecondPage.men3.getText().equalsIgnoreCase("french fries")) {
                    String sql = "INSERT INTO detail_transaksi VALUES('" + kt.getText() + "' ,'03','" + FirstPage.jSpinner3.getModel().getValue().toString() + "','" + SecondPage.ment3.getText() + "' )";
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                } else {
                    System.out.println("Detail menu 3 kosong");
                }
                if (SecondPage.men4.getText().equalsIgnoreCase("fried rice")) {
                    String sql = "INSERT INTO detail_transaksi VALUES('" + kt.getText() + "' ,'04','" + FirstPage.jSpinner4.getModel().getValue().toString() + "','" + SecondPage.ment4.getText() + "' )";
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                } else {
                    System.out.println("Detail menu 4 kosong");
                }
                if (SecondPage.men5.getText().equalsIgnoreCase("Pizza")) {
                    String sql = "INSERT INTO detail_transaksi VALUES('" + kt.getText() + "' ,'09','" + FirstPage.jSpinner5.getModel().getValue().toString() + "','" + SecondPage.ment5.getText() + "' )";
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                } else {
                    System.out.println("Detail menu 5 kosong");
                }
                if (SecondPage.men6.getText().equalsIgnoreCase("lemon tea")) {
                    String sql = "INSERT INTO detail_transaksi VALUES('" + kt.getText() + "' ,'06','" + FirstPage.jSpinner6.getModel().getValue().toString() + "','" + SecondPage.ment6.getText() + "' )";
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                } else {
                    System.out.println("Detail menu 6 kosong");
                }
                if (SecondPage.men7.getText().equalsIgnoreCase("coffe")) {
                    String sql = "INSERT INTO detail_transaksi VALUES('" + kt.getText() + "' ,'07','" + FirstPage.jSpinner7.getModel().getValue().toString() + "','" + SecondPage.ment7.getText() + "' )";
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                } else {
                    System.out.println("Detail menu 7 kosong");
                }
                if (SecondPage.men8.getText().equalsIgnoreCase("tea")) {
                    String sql = "INSERT INTO detail_transaksi VALUES('" + kt.getText() + "' ,'08','" + FirstPage.jSpinner8.getModel().getValue().toString() + "','" + SecondPage.ment8.getText() + "' )";
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                } else {
                    System.out.println("Detail menu 8 kosong");
                }
                if (SecondPage.men9.getText().equalsIgnoreCase("Milkshake")) {
                    String sql = "INSERT INTO detail_transaksi VALUES('" + kt.getText() + "' ,'05','" + FirstPage.jSpinner9.getModel().getValue().toString() + "','" + SecondPage.ment9.getText() + "' )";
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                } else {
                    System.out.println("Detail menu 9 kosong");
                }
                if (SecondPage.men10.getText().equalsIgnoreCase("soda")) {
                    String sql = "INSERT INTO detail_transaksi VALUES('" + kt.getText() + "' ,'10','" + FirstPage.jSpinner10.getModel().getValue().toString() + "','" + SecondPage.ment10.getText() + "' )";
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                } else {
                    System.out.println("Detail menu 10 kosong");
                }
                this.setVisible(false);
                new FourthPages().setVisible(true);
                JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
                FourthPages.jLabel1.setText("Uang Pas");
                FourthPages.jLabel5.setText("Non Tunai");
                new Qrpage().setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Detail Transaksi Error!\n" + e.getMessage());
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, "Transaksi Error!\nTerdapat Kode Transaksi Yang Sama!!\n" + e.getMessage());
        }

    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IniGmbr/NIew/bunon.png")));

    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IniGmbr/NIew/bunon1.png")));
    }//GEN-LAST:event_jLabel1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThirdPages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThirdPages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThirdPages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThirdPages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThirdPages().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField kt;
    public static javax.swing.JLabel mab;
    private javax.swing.JTextField nm;
    private javax.swing.JTextField np;
    // End of variables declaration//GEN-END:variables
}
